SEPERATOR_LENGTH = 80
MELON_PRICES = {"Musk": 1.15, "Hybrid": 1.30, "Watermelon": 1.75, "Winter": 4.00}

def get_melon_amount(file_name):
    """Get the amount of each type of melon sold."""
    file_obj = open(file_name)
    file_contents = file_obj.read()
    file_obj.close()

    # Split the file contents into a list of lines
    melon_orders = file_contents.split("\n")

    melon_tallies = {"Musk":0, "Hybrid":0, "Watermelon":0, "Winter": 0}

    for order in melon_orders:
        if order != "":
            # Ignore empty lines
            order_data = order.split("|")
            melon_type = order_data[1]
            melon_count = int(order_data[2])
            melon_tallies[melon_type] += melon_count

    return melon_tallies

def print_revenue(melon_tallies):
    """Print the revenue from each melon type."""
    for melon_type in melon_tallies:
        melon_count = melon_tallies[melon_type]
        # Round the individual melon price and melon revenue to two decimal places
        price = round(MELON_PRICES[melon_type], 2)
        revenue = round(price * melon_count, 2)

        print "We sold " + str(melon_count) + " " + melon_type + " melons at " + str(price) + " each for a total of " + str(revenue)

    return revenue

def seperate_sales_types(file_name):
    """Find each sale type (phone or internet) and return the revenue generated from each."""
    file_obj = open(file_name)
    file_contents = file_obj.read()
    file_obj.close()

    # Split the file contents into a list of lines
    melon_orders = file_contents.split("\n")

    phone_revenue = 0
    internet_revenue = 0

    for order in melon_orders:
        if order != "":
            # Ignore empty lines
            order_data = order.split("|")
            if order_data[2] == "ONLINE":
                internet_revenue += float(order_data[3])
            else:
                phone_revenue += float(order_data[3])

    # Round the revenue generated by each sale type to two decimal places
    phone_revenue = round(phone_revenue, 2)
    internet_revenue = round(internet_revenue, 2)

    return phone_revenue, internet_revenue

def print_report():
    """Print out the melon sales report."""
    melon_tallies = get_melon_amount("orders_by_type.txt")

    print "*" * SEPERATOR_LENGTH
    print_revenue(melon_tallies)
    print "*" * SEPERATOR_LENGTH

    phone_revenue, internet_revenue = seperate_sales_types("orders_with_sales.txt")
    print "Salespeople generated " + str(phone_revenue) + " in revenue."
    print "Internet sales generated " + str(internet_revenue) + " in revenue."
    
    if phone_revenue > internet_revenue:
        print "Guess there's some value to those salespeople after all."
    else:
        print "Time to fire the sales team! Online sales rule all!"
    print "*" * SEPERATOR_LENGTH

print_report()
